name: Test

on: [push, pull_request]

jobs:
  test:
    name: on ruby ${{matrix.ruby}}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6, 2.7, 3.0, head]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}

    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3

    - name: RSpec
      run: bundle exec rspec
